name: simple_audio
version: 0.9.0
author: John McCutchan <john@johnmccutchan.com>
description: A simple audio library for video games.
homepage: https://github.com/johnmccutchan/simple_audio
dependencies:
  asset_pack:
    git: https://github.com/johnmccutchan/asset_pack.git
  browser: any
  hop: any
